### ISSUE TITLE
.sfs files not working for me

### ISSUE THREAD

**Issue by TryTryAgain** [al2me6/vscode-ksp-cfg-support#1]
Hello, thanks for working on and releasing this! It's only working for `.craft` and `.cfg` files for me though. How can I help troubleshoot? I'm on Windows 10 using the latest stable version of vscode. `.craft` and `.cfg` files show up with syntax highlighting as expected but all of my `.sfs` files do not (I've tested from my current persistent save,  which is ~20MB and ~1million lines, I believe is borked and why I stumbled upon this extension, and even a simple save I had from many months ago...pre-mods and not nearly as large). I've gone through with a simple regex search `\S}` and confirmed no results that would point to your listed known issue: "Erratic behavior when a closing brace is not placed on its own line".

**Comment by al2me6** [comment]
That is a very large file indeed. Is the file entirely un-highlighted or are parts of it highlighted (correctly or not)? It is possible that VSCode has decided to turn off syntax highlighting for large files. It'd be helpful if you could send me the save file in question.

But yes, I've found a few more edge cases regarding highlighting of rvalues (if it can be called that), though I suspect they'll be difficult to fix, considering how ill-defined parts of the syntax are. I've got an idea for a partial rewrite in the works; perhaps it will help. (Look out for version 0.2).

**Comment by al2me6** [comment]
Hey, sorry that I haven't had a chance to look at this extension for this long. I've released 0.2 now, it should fix all the issues I'm aware of. 

I did test some `sfs`es and they seemed to work well.
